language: node_js
node_js:
- node
notifications:
  email: false
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: hhDVZcSWbt+LYHX76qdc2RTU+Qq6c4Htr18B3OwevfPclId6jsOCJWnP38dmPnTy6ZGSmpDz9dNUVDxtq6/F5/m9U0YmlFxtm5zFWAA6mugDGqQw7Ga/VCqyO4caZX//14HnrZNc7rUC0du/UYW7YMMZ7fvHqDR3NWpLsSwILC0nmOf+I5IkOQ321fvWvybWTCOm9O3HfXAIG9zIqvTxFRn6dgItqdXxkY3GuCoGyVXUi4ssacWKSHSKeqjwhLhkIUq9Si8AWGX2z7cAMElIXDl2+H8LqKVeWuN244sGAz5ZBAT3Brk+cieEM3ZCV2oToQ7guliGScfaE7sKzNxz21EFhK+vaISMN4RaU1uM6opQ5J4Oe+cWW6r/ubsJUKYElq0L5rLijXhAmK4AzWe2H5vm1fizwGJ0PPDDLqjvRGH5AwAE9e1TTEZCG8UIOA6RSI0a4w57Qqo7azI8cxCKQh5GVpeGWJ/zFyxggG4HklDNmi78Nmu5RbYzspOoDfT4wNUUcUBMX/5mPw9kQa34qYjR9RIy/M62zONAtLKhhaPHxnay5E4lv6r7vLs7l//HNNgqIaLTjHkUM7Rh2XbcSvJKMuU6XykdHC75kVS4604QY+63zplm5V23wntfEfdWwJETOs6yYA54iV6V8xK88d7KZrMiPUI7xoAmoQMZ2jI=
  app: careerexplore-deploy
  skip_cleanup: true
